/**
 * One icon file per spell concept — jobs share art; never regenerate Cure × N.
 * Prefer these paths from abilityIconUrl before /icons/abilities/{id}.png.
 */
export const SHARED_ABILITY_ICON: Record<string, string> = {
  rest: "/icons/abilities/rest.png",

  // TIM bare ids (canonical filenames)
  cure: "/icons/abilities/cure.png",
  cure_ii: "/icons/abilities/cure_ii.png",
  cure_iii: "/icons/abilities/cure_iii.png",
  cure_iv: "/icons/abilities/cure_iv.png",
  haste: "/icons/abilities/haste.png",
  hastega: "/icons/abilities/hastega.png",
  slow: "/icons/abilities/slow.png",
  slow_ii: "/icons/abilities/slow_ii.png",
  slowga: "/icons/abilities/slowga.png",
  bind: "/icons/abilities/bind.png",
  bindga: "/icons/abilities/bindga.png",
  dispel: "/icons/abilities/dispel.png",
  dispelga: "/icons/abilities/dispelga.png",
  gravity: "/icons/abilities/gravity.png",
  gravity_ii: "/icons/abilities/gravity_ii.png",
  gravityga: "/icons/abilities/gravityga.png",

  // Knight — same art as TIM / Cleric
  kn_cure: "/icons/abilities/cure.png",
  kn_cure_ii: "/icons/abilities/cure_ii.png",
  kn_cure_iii: "/icons/abilities/cure_iii.png",
  kn_cure_iv: "/icons/abilities/cure_iv.png",
  kn_protect: "/icons/abilities/protect.png",
  kn_protect_ii: "/icons/abilities/protect_ii.png",
  kn_protect_iii: "/icons/abilities/protect_iii.png",
  kn_shell: "/icons/abilities/shell.png",
  kn_shell_ii: "/icons/abilities/shell_ii.png",
  kn_shell_iii: "/icons/abilities/shell_iii.png",
  kn_banish: "/icons/abilities/banish.png",
  kn_banish_ii: "/icons/abilities/banish_ii.png",
  kn_holy: "/icons/abilities/holy.png",
  kn_flash: "/icons/abilities/flash.png",

  // Battle Mage
  bm_cure: "/icons/abilities/cure.png",
  bm_cure_ii: "/icons/abilities/cure_ii.png",
  bm_cure_iii: "/icons/abilities/cure_iii.png",
  bm_cure_iv: "/icons/abilities/cure_iv.png",
  bm_protect: "/icons/abilities/protect.png",
  bm_shell: "/icons/abilities/shell.png",
  bm_haste: "/icons/abilities/haste.png",
  bm_slow: "/icons/abilities/slow.png",
  bm_dispel: "/icons/abilities/dispel.png",
  bm_bind: "/icons/abilities/bind.png",
  bm_gravity: "/icons/abilities/gravity.png",

  // Sorcerer — shared enfeeble / utility concepts
  sc_root_sigil: "/icons/abilities/bind.png",
  sc_unweave: "/icons/abilities/dispel.png",

  // Cleric
  cl_cure: "/icons/abilities/cure.png",
  cl_cure_ii: "/icons/abilities/cure_ii.png",
  cl_cure_iii: "/icons/abilities/cure_iii.png",
  cl_cure_iv: "/icons/abilities/cure_iv.png",
  cl_cure_v: "/icons/abilities/cure_iv.png",
  cl_curaga: "/icons/abilities/cure.png",
  cl_curaga_ii: "/icons/abilities/cure_ii.png",
  cl_curaga_iii: "/icons/abilities/cure_iii.png",
  cl_protect: "/icons/abilities/protect.png",
  cl_protect_ii: "/icons/abilities/protect_ii.png",
  cl_protect_iii: "/icons/abilities/protect_iii.png",
  cl_protectra: "/icons/abilities/protect.png",
  cl_shell: "/icons/abilities/shell.png",
  cl_shell_ii: "/icons/abilities/shell_ii.png",
  cl_shell_iii: "/icons/abilities/shell_iii.png",
  cl_shellra: "/icons/abilities/shell.png",
  cl_banish: "/icons/abilities/banish.png",
  cl_banish_ii: "/icons/abilities/banish_ii.png",
  cl_holy: "/icons/abilities/holy.png",
  cl_flash: "/icons/abilities/flash.png",
  cl_haste: "/icons/abilities/haste.png",
  cl_slow: "/icons/abilities/slow.png",
  cl_regen: "/icons/abilities/cure.png",
  cl_regen_ii: "/icons/abilities/cure_ii.png",
  cl_regen_iii: "/icons/abilities/cure_iii.png",
  cl_raise: "/icons/abilities/cure.png",
  cl_raise_ii: "/icons/abilities/cure_ii.png",
  cl_reraise: "/icons/abilities/cure_iii.png",
  cl_paralyze: "/icons/abilities/paralyga.png",
  cl_silence: "/icons/abilities/silencega.png",
};

/** Spell concepts that already have art — do not GenerateImage again. */
export const SHARED_SPELL_ICON_CONCEPTS = [
  "cure",
  "cure_ii",
  "cure_iii",
  "cure_iv",
  "cure_v",
  "curaga",
  "curaga_ii",
  "curaga_iii",
  "protect",
  "protect_ii",
  "protect_iii",
  "protectra",
  "shell",
  "shell_ii",
  "shell_iii",
  "shellra",
  "banish",
  "banish_ii",
  "holy",
  "flash",
  "haste",
  "hastega",
  "slow",
  "slow_ii",
  "slowga",
  "regen",
  "regen_ii",
  "regen_iii",
  "raise",
  "raise_ii",
  "reraise",
  "rest",
  "bind",
  "bindga",
  "dispel",
  "dispelga",
  "gravity",
  "gravity_ii",
  "gravityga",
  "sleep",
  "sleepga",
  "blind",
  "drain",
  "aspir",
  "stun",
  "warp",
] as const;
